In [1]:
import pandas as pd

In [25]:
df = pd.read_csv(r"C:\Users\alkan\Downloads\Başlıksız form.csv\Başlıksız form.csv")


In [26]:
x = df.iloc[:,:5]
y = df.iloc[:,5:9]
y

Robotla olan etkileşiminizi genel olarak nasıl değerlendirirsiniz?  (1 En Kötü - 5 En İyi)  \
0                                                   4                                             
1                                                   4                                             
2                                                   5                                             
3                                                   5                                             
4                                                   4                                             
5                                                   5                                             
6                                                   5                                             
7                                                   5                                             
8                                                   5                                             
9                                                   4                                             
10                                                  4                                             
11                                                  4                                             
12                                                  5                                             
13                                                  5                                             
14                                                  5                                             
15                                                  5                                             
16                                                  5                                             
17                                                  2                                             
18                                                  5                                             
19                                                  4                                             
20                                                  4                                             
21                                                  4                                             

     Robotla konuşurken kendinizi ne kadar rahat hissettiniz? (1 En Düşük - 5 En Yüksek).1  \
0                                                   5                                        
1                                                   5                                        
2                                                   4                                        
3                                                   5                                        
4                                                   5                                        
5                                                   4                                        
6                                                   5                                        
7                                                   4                                        
8                                                   4                                        
9                                                   3                                        
10                                                  3                                        
11                                                  2                                        
12                                                  5                                        
13                                                  5                                        
14                                                  5                                        
15                                                  5                                        
16                                                  5                                        
17                                 

In [56]:
df.iloc[:,9:].mean()

Yüz yüze bir diyalogdaymışsınız gibi hissettiniz mi? (1  Hayır Hissetmedim - 5 Evet Hisettim)    3.954545
Robotun yüzünün olması, sizinle olan etkileşimi nasıl etkiledi?  (1 En kötü - 5 En iyi)          4.181818
dtype: float64

In [27]:
from scipy.stats import shapiro

In [28]:
x = x.to_numpy()[:,1:]
y = y.to_numpy()[:,0:]

In [29]:
x_mean = x.mean(axis=1)
x_mean

array([3.0, 3.0, 3.25, 4.75, 3.5, 4.5, 2.25, 2.25, 4.5, 3.75, 3.0, 3.0,
       4.0, 5.0, 4.75, 4.75, 2.0, 3.0, 4.25, 4.0, 4.0, 3.25], dtype=object)

In [32]:
x_mean.mean()

3.625

In [34]:
x_mean.std()

0.8717472006368485

In [35]:
y_mean.mean()

4.3522727272727275

In [36]:
y_mean.std()

0.5918916655957008

In [30]:
y_mean = y.mean(axis=1)
y_mean

array([4.5 , 4.5 , 4.5 , 4.75, 4.75, 4.25, 5.  , 4.25, 4.75, 4.  , 3.75,
       3.  , 5.  , 5.  , 5.  , 5.  , 4.75, 3.  , 3.75, 4.25, 4.25, 3.75])

In [31]:
shapiro(x_mean - y_mean)  # Farkların dağılımına bakılır

ShapiroResult(statistic=0.8808813861147738, pvalue=0.012558887403498946)

In [37]:
from scipy.stats import wilcoxon

In [43]:
wilcoxon(x_mean.tolist(), y_mean.tolist())  # İki bağımlı örneklem için Wilcoxon testi

WilcoxonResult(statistic=12.5, pvalue=0.0013646203600395654)

In [50]:
x[:,0]

array([4, 3, 3, 5, 3, 5, 3, 3, 5, 4, 4, 2, 4, 5, 5, 5, 3, 4, 5, 4, 4, 4],
      dtype=object)

In [54]:
results = {}

for i in range(4):
    x_vals = x[:,i]
    y_vals = y[:,i]
    # Wilcoxon testi
    stat, p = wilcoxon(x_vals.tolist(), y_vals.tolist())

    results[f"{i}"] = {
        "p_value": round(p, 4),
        "mean_x (yüzsüz)": round(x_vals.mean(), 2),
        "mean_y (yüzlü)": round(y_vals.mean(), 2),
        "yorum": "Anlamlı fark VAR" if p < 0.05 else "Anlamlı fark YOK"
    }

# DataFrame olarak göster
results_df = pd.DataFrame(results).T
print(results_df)

  p_value mean_x (yüzsüz) mean_y (yüzlü)             yorum
0  0.0495            3.95           4.45  Anlamlı fark VAR
1  0.0596            3.55           4.14  Anlamlı fark YOK
2   0.011            3.68           4.32  Anlamlı fark VAR
3  0.0008            3.32            4.5  Anlamlı fark VAR
